In [7]:
import numpy as np
import warnings
warnings.filterwarnings('ignore')

In [2]:
# Array Creation

In [15]:
a = np.array([1,2,3,4,5])
print(a)
print(type(a))
a.ndim

[1 2 3 4 5]
<class 'numpy.ndarray'>


1

In [5]:
# Zero dimentional array

z = np.array(10)
print(z)
print(type(z))
z.ndim

10
<class 'numpy.ndarray'>


0

In [8]:
# Two dimensional array

t = np.array([[1,2,3,4,5],
             [6,7,8,9,2,4]])
print(t)
print(type(t))
t.ndim

[list([1, 2, 3, 4, 5]) list([6, 7, 8, 9, 2, 4])]
<class 'numpy.ndarray'>


1

In [11]:
# Three dimensional array

T = np.array([[[[1,2,3],
               [4,5,6],
             [7,8,9],
              [3,5,5,2,5]]]])
print(T)
print(type(T))
T.ndim

[[[list([1, 2, 3]) list([4, 5, 6]) list([7, 8, 9]) list([3, 5, 5, 2, 5])]]]
<class 'numpy.ndarray'>


3

In [12]:
# Change the data type of the array elements.

In [18]:
a = np.array([[1,2,3,4,5]], dtype = 'float')
a

array([[1., 2., 3., 4., 5.]])

In [20]:
i = np.array([[1.4,1.3,4.2,4.5,6.3,3.73]], dtype = 'int')
i

array([[1, 1, 4, 4, 6, 3]])

Other ways of creating an array
1. arange
2. linspace
3. zeros
4. ones

In [22]:
# arange
a = np.arange(10, 21)
a

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20])

In [32]:
# linspace
l = np.linspace(1,20,22, retstep= True)
l

(array([ 1.        ,  1.9047619 ,  2.80952381,  3.71428571,  4.61904762,
         5.52380952,  6.42857143,  7.33333333,  8.23809524,  9.14285714,
        10.04761905, 10.95238095, 11.85714286, 12.76190476, 13.66666667,
        14.57142857, 15.47619048, 16.38095238, 17.28571429, 18.19047619,
        19.0952381 , 20.        ]),
 0.9047619047619048)

In [33]:
z= np.zeros([2,4])
z

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [36]:
o= np.ones([3,5])
o

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

Slicing and indexing of array

In [37]:
a = np.array([[1,2,3,4], [5,6,7,8]])
a

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [38]:
a[0][0]

1

In [39]:
a[1][2]

7

In [40]:
a[:, 1:]

array([[2, 3, 4],
       [6, 7, 8]])

In [41]:
# Aggregate Function

In [42]:
a = np.array([1,2,3,4,5,6])
a

array([1, 2, 3, 4, 5, 6])

In [43]:
a.sum()

21

In [44]:
a.min()

1

In [45]:
a.max()

6

In [46]:
a.mean()

3.5

In [47]:
a.std()

1.707825127659933

Stacking
- join 2 different array

In [48]:
a = np.array([1,2,3])
b = np.array([4,5,6])

In [49]:
c = np.vstack([a,b])
c

array([[1, 2, 3],
       [4, 5, 6]])

In [51]:
d = np.hstack([a,b])
d

array([1, 2, 3, 4, 5, 6])